import Head from "next/head";
import Image from "next/image";

import Link from "next/link";
import { FaLinkedinIn, FaFacebook, FaMailBulk, FaGithub } from "react-icons/fa";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="flex  text-3xl sm:text-5xl space-x-4 pt-36  font-bold justify-center  text-[#fe0000] hover:text-black items-center">
          <h1>ARIF</h1>
          <h1 className="text-black hover:text-[#fe0000]">CHAUDHARY</h1>
        </div>
        <div className="flex sm:text-3xl text-xl pt-5 space-x-4 animate-pulse font-bold justify-center text-gray-600 items-center">
          <h1>Creative </h1>
          <h1 className=" text-blue-700">Developer</h1>
        </div>
        <div className="flex pt-5 justify-center items-center">
          <button className="rounded-full p-2 pl-7 pr-7 bg-gradient-to-r from-purple-500 to-pink-500  hover:from-violet-700 hover:to-fuchsia-700 text-white">
            <Link href="/contact">
              <a>Get in Touch</a>
            </Link>
          </button>
        </div>
        <div className="flex pt-20 justify-center items-center space-x-6 text-2xl ">
          <div>
            <Link href="https://www.linkedin.com/in/muhammad-arif-raza-6b7bb3190/">
              <a>
                <FaLinkedinIn />
              </a>
            </Link>
          </div>
          <div>
            <Link href=" https://www.facebook.com/profile.php?id=100005120626896">
              <a>
                <FaFacebook />
              </a>
            </Link>
          </div>
          <div>
            <Link href="  https://github.com/arifch786">
              <a>
                <FaGithub />
              </a>
            </Link>
          </div>
          <div>
            <FaMailBulk />
          </div>
        </div>
      </div>
    </div>
  );
}
